### ISSUE TITLE
Documentation Meta Ticket

### ISSUE THREAD

**Issue by svx** [plone/guillotina#913]
List with items to change and/or improve related to documentation

- [ ] Move *design* docs out of *development* and into the *about* chapter.
- [ ] Add *Key Points*
- [ ] Move *component architecture* docs out of *development* and into the *about* chapter
- [ ] Remove double install instructions (training and development) have them once and link/reference
